@startuml
'https://plantuml.com/class-diagram


struct FingerForceMeasured {
thumb : double
index : double
middle : double
ring : double
little : double
palm : double
}

struct IceGloveServoPos {
thumb : int
index : int
middle : int
ring : int
little : int
palm : int
}

class IceTeslaGlove {
+ IceTeslaGlove()
- timer_callback()
- calculate_servo_pos()
- update_force_feedback()
- update_servo_pos()
}

IceTeslaGlove --|> Node
FingerForceMeasured --|> IceTeslaGlove
IceGloveServoPos --|> IceTeslaGlove



@enduml