//
// Created by biomech on 27.01.24.
//

#ifndef HAPTICGRIPPERWS_SRC_ICETESLAGLOVE_SRC_ICE_TESLA_GLOVE_HH_
#define HAPTICGRIPPERWS_SRC_ICETESLAGLOVE_SRC_ICE_TESLA_GLOVE_HH_

class ice_tesla_glove {

};

#endif //HAPTICGRIPPERWS_SRC_ICETESLAGLOVE_SRC_ICE_TESLA_GLOVE_HH_
